# Generated by Django 5.1.1 on 2025-04-01 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_alter_posts_arrival_date_alter_posts_depart_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateField(auto_now_add=True)),
                ('logged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_post', to='posts.posts')),
            ],
        ),
    ]
