# Generated by Django 5.1.1 on 2025-04-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_history_logged_user_history_visitor'),
        ('posts', '0009_alter_posts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_post', to='posts.posts'),
        ),
    ]
