# Generated by Django 5.1.1 on 2025-04-30 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='post',
        ),
        migrations.AddField(
            model_name='history',
            name='arrival_date',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='history',
            name='arrival_place',
            field=models.CharField(default='16:07:41', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='depart_date',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='history',
            name='depart_place',
            field=models.CharField(default='a', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
