# Generated by Django 5.1.1 on 2025-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_remove_history_post_history_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='arrival_place',
            field=models.CharField(default='a', max_length=70),
        ),
        migrations.AlterField(
            model_name='history',
            name='depart_place',
            field=models.CharField(default='a', max_length=70),
        ),
    ]
