# Generated by Django 5.1.1 on 2025-04-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_history_post'),
        ('posts', '0009_alter_posts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='history',
            name='arrival_place',
        ),
        migrations.RemoveField(
            model_name='history',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='history',
            name='depart_place',
        ),
        migrations.RemoveField(
            model_name='history',
            name='price',
        ),
        migrations.AlterField(
            model_name='history',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_post', to='posts.posts'),
        ),
    ]
