# Generated by Django 5.1.1 on 2025-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ppermis_ic',
            field=models.ImageField(null=True, upload_to='backend/profile/permis_ic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_pic',
            field=models.ImageField(null=True, upload_to='backend/profile/pfimage'),
        ),
    ]
