# Generated by Django 5.1.1 on 2025-03-25 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depart_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('depart_place', models.CharField(max_length=70)),
                ('arrival_place', models.CharField(max_length=70)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
