# Generated by Django 5.1.1 on 2025-03-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='autor',
        ),
        migrations.AddField(
            model_name='posts',
            name='animals_autorised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='number_of_places',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='smoker',
            field=models.BooleanField(default=False),
        ),
    ]
