# Generated by Django 5.1.1 on 2025-03-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_autor_posts_animals_autorised_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='arrival_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='depart_date',
            field=models.TimeField(),
        ),
    ]
