# Generated by Django 5.1.1 on 2025-03-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_rating',
            name='autor',
        ),
        migrations.AddField(
            model_name='comments_rating',
            name='author_comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
